twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # cache: false

    paths: 
        '%kernel.project_dir%/public/assets/mail/css': styles
        '%kernel.project_dir%/public/assets/mail/images': images
        '%kernel.project_dir%/templates/mail/send':

when@test:
    twig:
        strict_variables: true
