twig:
    default_path: '%kernel.project_dir%/templates'

    paths: 
        '%kernel.project_dir%/public/assets/css': styles
        '%kernel.project_dir%/public/assets/images': images
        '%kernel.project_dir%/public/assets/templates': 

when@test:
    twig:
        strict_variables: true
